repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.23"
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.0"
    hooks:
      - id: pyproject-fmt
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run --frozen ruff format
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: uv run --frozen ruff check --fix
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: deptry
        name: deptry
        entry: uv run --frozen deptry src
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: import-linter
        name: import-linter
        entry: uv run --frozen lint-imports
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run --frozen pyright
        language: system
        always_run: true
        pass_filenames: false
