coverage:
  status:
    project:
      default:
        enabled: yes
        target: 0.95
        threshold: 0.05
    patch:
      default:
        enabled: yes
        target: 1
        threshold: 0.01