[project]
name = "usethis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mergedeep>=1.3.4",
    "packaging>=24.1",
    "pydantic>=2.9.2",
    "requests>=2.32.3",
    "rich>=13.8.1",
    "ruamel-yaml>=0.18.6",
    "tomlkit>=0.13.2",
    "typer>=0.12.5",
]

[project.scripts]
usethis = "usethis.__main__:app"

[dependency-groups]
test = [
    "coverage[toml]>=7.6.3",
    "gitpython>=3.1.43",
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
    "pytest-emoji>=0.2.0",
    "pytest-md>=0.2.0",
]
dev = [
    "deptry>=0.20.0",
    "import-linter>=2.1",
    "pre-commit>=4.0.1",
    "ruff>=0.7.0",
]

[tool.uv]
default-groups = ["test", "dev"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
src = ["src"]
line-length = 88

[tool.ruff.lint]
select = ["C4", "E4", "E7", "E9", "F", "FURB", "I", "PLE", "PLR", "RUF", "SIM", "UP"]


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = [
    "--import-mode=importlib",
]

[tool.coverage.run]
source = ["src"]
omit = ["*/pytest-of-*/*"]

[tool.importlinter]
root_packages = ["usethis"]

[[tool.importlinter.contracts]]
name = "Modular Design"
type = "layers"
layers = [
    "__main__",
    "_interface",
    "_tool",
    "_integrations",
    "_utils"
]
containers=["usethis"]
exhaustive=true
