[project]
name = "usethis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gitpython>=3.1.43",
    "packaging>=24.1",
    "pydantic>=2.9.2",
    "requests>=2.32.3",
    "rich>=13.8.1",
    "ruamel-yaml>=0.18.6",
    "tomlkit>=0.13.2",
    "typer>=0.12.5",
]

[project.scripts]
usethis = "usethis.__main__:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.2",
    "pytest-md>=0.2.0",
    "pytest-emoji>=0.2.0",
    "deptry>=0.20.0",
]
