name: CI
on:
    workflow_dispatch:
    push:
      branches: ['main', 'develop']
    pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup uv and handle its cache
        uses: hynek/setup-cached-uv@49a39f911c85c6ec0c9aadd5a426ae2761afaba2 # v2.0.0
        
      - name: Setup dependencies
        run: |
          ls ./.requirements
          uv pip install --system -r ./.requirements/${{ matrix.python-version }}-${{ runner.os }}.txt
          uv pip install --system pytest pytest-md pytest-emoji

      - name: Run pytest
        uses: pavelzw/pytest-action@510c5e90c360a185039bea56ce8b3e7e51a16507 # v2.2.0
        with:
          custom-arguments: tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]
