name: CI
on:
    workflow_dispatch:
    push:
      branches: ['main', 'develop']
    pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup uv and Handle Its Cache
        uses: hynek/setup-cached-uv@v2.0.0
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: uv sync --python-preference system
    
      - name: Run pytest
        uses: pavelzw/pytest-action@v2.2.0
        with:
          custom-arguments: tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]
